name: "CI"

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  release:
    if: github.repository == 'fernandonogueira/statuspage-exporter'
    name: Release
    environment: release
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      # Dockerhub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
