name: "CI"

on:
  push:
    branches: [ "main" ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  release:
    permissions:
      contents: write
    if: github.repository == 'fernandonogueira/statuspage-exporter'
    name: Release
    environment: release
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      # Dockerhub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: go-semantic-release/action@v1
        with:
          custom-arguments: --provider-opt github_use_compare_commits=true
          hooks: goreleaser
          changelog-file: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
