name: Release Helm
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Chart | Build | Push
      working-directory: "helm/statuspage-exporter"
      run: |
        echo $GITHUB_TOKEN | helm registry login ghcr.io/fernandonogueira --username fernandonogueira --password-stdin
        helm package .
        helm push statuspage-exporter-chart-${{ github.event.inputs.tag }}.tgz oci://ghcr.io/fernandonogueira/statuspage-exporter
        
